version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Building...
      - aws cloudformation package --template-file final-network-stack.yml --s3-bucket afg-project3-s3 --output-template-file networkoutputTemplate.yaml
artifacts:
  files:
    - final-network-stack.yml
    - networkoutputTemplate.yaml
