AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template Route53_A: Sample template showing how to
  create an Amazon Route 53 A record that maps to the public IP address of an
  EC2 instance. It assumes that you already have a Hosted Zone registered with
  Amazon Route 53. **WARNING** This template creates an Amazon EC2 instance. You
  will be billed for the AWS resources used if you create a stack from this
  template.

Resources:
  # AFGDNS:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: Z10110271SXOJ2FJT4H1H
  #     Name: afg.puma.cloudspacellc.com
  #     Type: A
  #     TTL: '300'
  #     ResourceRecords:
  #     - 192.168.0.0
  #     - 192.168.2.0
  GeolocationRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Creating records for US user
      HostedZoneId: Z10110271SXOJ2FJT4H1H
      RecordSets:
      - Name: afg.puma.cloudspacellc.com
        ResourceRecords: 
        - !ImportValue afg-web-stack-AFGApplicationLoadBalancer
        TTL: '60'
        SetIdentifier: Frontend One        
        Type: CNAME
        GeoLocation:
          CountryCode: 'US'
      - Name: afg.puma.cloudspacellc.com
        ResourceRecords: 
        - !ImportValue afg-s3-stack-AFGSTATICS3Bucket
        TTL: '60'
        SetIdentifier: Frontend Two        
        Type: CNAME
        GeoLocation:
          CountryCode: '*'  
      
Outputs:
  DomainName:
    Description: Fully qualified domain name
    Value: !Ref GeolocationRecord